# This workflow isn't meant to be run. It exists solely for the purpose of using it with
# https://github.com/typesafegithub/github-workflows-kt. Thanks to defining used actions this way, the library can
# generate type-safe bindings, and dependency updating bots like Renovate or Dependabot can update actions' versions.

on:
  push:
    branches: [this-branch-must-never-be-created]

jobs:
  some-job:
    runs-on: ubuntu-latest
    steps:
      # List used actions below, as subsequent "- uses" items:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
      - uses: gradle/gradle-build-action@v2
      - uses: entrostat/git-secret-action@v4
      - uses: ruby/setup-ruby@v1
      - uses: softprops/action-gh-release@v1