name: Dependency Analysis
on: push
jobs:
  analyse:
    runs-on: ubuntu-latest
    name: Dependency analysis
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build-health
        run: ./gradlew buildHealth
      - name: artifact-upload
        uses: actions/upload-artifact@v3
        with:
          name: dependency-analysis-output
          path: build/reports/dependency-analysis/build-health-report.txt